### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/project-final-Byte-Busters#3]
Dear Byte Busters: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |       3 |
| Proposal | 5         |      3.5  |
| Workflow | 1         |      1  |
| Teamwork | 1         |      1  |
| Total    | 10        |     8.5   |

Proposal: as was identified in your peer-reviews, there is no analysis plan, so its not clear what you will be doing to address objectives / questions.

**Comment by riyanshibohra** [comment]
Following our recent conversation in the last class, you mentioned that the points for the 'Data' section of our proposal would be automatically revised. This is due to our inclusion of the actual column names in the proposal.qmd file, despite it not being published on the site at that time. I understand this adjustment will be made directly to our grade, eliminating the need for a formal regrade request for the same.

Apart from that, we have now included an analysis plan in the proposal, addressing your second point of feedback. We would appreciate a regrade for this newly integrated section of the analysis plan.

**Comment by Gchism94** [comment]
Your new score is 9.25/10 (the mid-point between 10 and your revised first score of 8.5). Good work.
