### ISSUE TITLE
Presentation feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/project-final-Byte-Busters#8]
Dear Byte-Busters: Below is the score breakdown for your presentation. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Time management     | 2         |   1     |
| Professionalism | 2         |     2   |
| Teamwork | 3         |   3     |
| Slides | 3         |    2    |
| Creativity Critical Thought | 3 | 3 |
| Content - Q1 | 6 | 5.5 |
| Content - Q2 | 6 |5.5 |
| Total    | 25        |     22   |

**Feedback**
Slides/content: The color scheme was not consistent in your visuals, where it should have been (e.g., categories should all have the same color schemes). Additionally, since the slides were not rendered, they aren't reproducible. 
Time management: Your presentation was >10 minutes long. Initially it should have been 5 minutes, but I extended it to 10.

**Comment by kendall-beaver** [comment]
Thank you, Greg, for your feedback and allowing us to present our final project with a PowerPoint presentation instead of the required Quarto presentation. We know that you were more than generous in allowing us to do this, which we don't take for granted, and we appreciate you presenting us with this challenge/final project as we all learned something from you, from the peers within our group, and from all of the groups in the class. We felt that everyone gave a meaningful, well-thought out and insightful presentation, which is a result of your teaching and guidance. 

Once again, we thank you for generosity and for giving us a meaningful and everlasting experience.

-The Byte Busters
